disabled_rules:
- unused_optional_binding
- line_length
- trailing_whitespace

excluded:
- Pods

opt_in_rules:
- operator_usage_whitespace
- vertical_whitespace_between_cases
- vertical_whitespace_closing_braces
