warning_threshold: 15

disabled_rules:
- unused_optional_binding
- trailing_whitespace

excluded:
- Pods
- ShoppingCart/Products
- ShoppingCart/Pods
- ShoppingCart/Frameworks
- ShoppingCart/Sources/App/AppDelegate.swift
- ShoppingCart/Sources/App/SceneDelegate.swift

opt_in_rules:
- operator_usage_whitespace
- vertical_whitespace_between_cases
- vertical_whitespace_closing_braces
